source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'activeadmin', github: 'activeadmin'
gem 'mysql2'
gem 'puma'
gem 'devise'
gem 'le'
gem 'tzinfo-data'
gem 'health-monitor-rails'
gem 'config'
gem 'rails-i18n'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'micromachine'
gem 'rack-ssl-enforcer'
gem 'awesome_print'
gem 'rack-mini-profiler'
gem 'ruby-units'

gem 'capybara', require: false
gem 'poltergeist', require: false

# woocommecre api
# gem 'woocommerce', github: 'shukydvir/woocommerce'

# API's
gem 'vacuum'
# gem 'peddler' # Amazon MWS API

# Parsers
# gem 'metainspector'
gem 'mechanize'

# sidekiq
gem 'sidekiq'
gem 'hiredis'
gem 'sinatra', require: nil
gem 'sidekiq-failures', github: 'mhfs/sidekiq-failures'
gem 'sidekiq-cron', '~> 0.4.0'
gem 'sidekiq-limit_fetch'
gem 'sidekiq-unique-jobs'

# notifications
gem 'slack-ruby-client'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  # gem 'guard-bundler'
  # gem 'guard-rails'
  # gem 'guard-rspec'
  # gem 'guard-brakeman'
  # gem 'guard-rubocop'
  # gem 'guard-annotate'
  # gem 'guard-sidekiq'
  # gem 'guard-spring'
  # gem 'mail_view'
  gem 'annotate'
  gem 'quiet_assets'
  # gem 'spring-commands-rspec'
  # gem 'spring'
  gem 'brakeman'
  gem 'bundler-audit'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'dotenv-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'launchy'
  gem 'rspec-sidekiq'
end
